### PR TITLE
fix organization.contact systems

### PR DESCRIPTION
**Pull request by ilaflamme-va**
https://vajira.max.gov/browse/API-11239?workflowName=Lighthouse+Default+Workflow&stepId=8

```
  "contact": [
    {
      "purpose": {
        "coding": [
          {
            "system": "https://va.gov/fhir/CodeSystem/organization-contactType",
            "code": "APPEAL",
            "display": "APPEAL"
          }
        ],
        "text": "APPEAL"
      },
      "telecom": [
        {
          "system": "phone",
          "value": "800-727-2220"
        }
      ]
    },
    {
      "extension": [
        {
          "url": "http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/via-intermediary",
          "valueReference": {
            "display": "SHANK-BILLING NAME: IN"
          }
        }
      ],
      "purpose": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/contactentity-type",
            "code": "BILL",
            "display": "BILL"
          }
        ],
        "text": "BILL"
      },
      "telecom": [
        {
          "system": "phone",
          "value": "800-727-222"
        }
      ]
    },
    {
      "purpose": {
        "coding": [
          {
            "system": "https://va.gov/fhir/CodeSystem/organization-contactType",
            "code": "DENTALCLAIMS",
            "display": "DENTALCLAIMS"
          }
        ],
        "text": "DENTALCLAIMS"
      }
    },
    {
      "purpose": {
        "coding": [
          {
            "system": "https://va.gov/fhir/CodeSystem/organization-contactType",
            "code": "INPTCLAIMS",
            "display": "INPTCLAIMS"
          }
        ],
        "text": "INPTCLAIMS"
      },
      "telecom": [
        {
          "system": "phone",
          "value": "813.626.1101"
        },
        {
          "system": "fax",
          "value": "800-255-6065"
        }
      ],
      "address": {
        "line": [
          "P.O. BOX 6003"
        ],
        "city": "JACKSONVILLE",
        "state": "FLORIDA",
        "postalCode": "322310014"
      }
    },
    {
      "purpose": {
        "coding": [
          {
            "system": "https://va.gov/fhir/CodeSystem/organization-contactType",
            "code": "OUTPTCLAIMS",
            "display": "OUTPTCLAIMS"
          }
        ],
        "text": "OUTPTCLAIMS"
      },
      "telecom": [
        {
          "system": "phone",
          "value": "(787)751-5656"
        }
      ],
      "address": {
        "line": [
          "PO BOX 2832"
        ],
        "city": "NEW YORK",
        "state": "NEW YORK",
        "postalCode": "101162832"
      }
    },
    {
      "purpose": {
        "coding": [
          {
            "system": "https://va.gov/fhir/CodeSystem/organization-contactType",
            "code": "RXCLAIMS",
            "display": "RXCLAIMS"
          }
        ],
        "text": "RXCLAIMS"
      },
      "address": {
        "line": [
          "PO BOX 14610"
        ],
        "city": "LEXINGTON",
        "state": "KENTUCKY",
        "postalCode": "405121234"
      }
    },
    {
      "purpose": {
        "coding": [
          {
            "system": "https://va.gov/fhir/CodeSystem/organization-contactType",
            "code": "INQUIRY",
            "display": "INQUIRY"
          }
        ],
        "text": "INQUIRY"
      },
      "telecom": [
        {
          "system": "phone",
          "value": "800-727-2221"
        }
      ]
    },
    {
      "purpose": {
        "coding": [
          {
            "system": "https://va.gov/fhir/CodeSystem/organization-contactType",
            "code": "PRECERT",
            "display": "PRECERT"
          }
        ],
        "text": "PRECERT"
      },
      "telecom": [
        {
          "system": "phone",
          "value": "800-955-5692"
        }
      ]
    },
    {
      "purpose": {
        "coding": [
          {
            "system": "https://va.gov/fhir/CodeSystem/organization-contactType",
            "code": "VERIFY",
            "display": "VERIFY"
          }
        ],
        "text": "VERIFY"
      },
      "telecom": [
        {
          "system": "phone",
          "value": "800-727-2223"
        }
      ]
    }
  ]
  ```

### CODE REVIEW

**Review by jhulbert-va — COMMENTED** [review]
Doc updates?

**Comment by ilaflamme-va** [comment]
Contact systems are ignored on writes, no need to update that documentation.

**Comment by bschofield-va** [comment]
image
 Doc updates are needed.

**Review by bschofield-va — CHANGES_REQUESTED** [review]
documentation updates ci vous plait

**Comment by ilaflamme-va** [comment]
Docs updated for new systems.

**Review by bschofield-va — APPROVED** [review]

**Pull request merged**
