### PR TITLE
API-10822: Drop /site support

### PR DESCRIPTION
**Pull request by jabando-va**

### CODE REVIEW

**Comment by bschofield-va** [comment]
Yanartas and VFQ are related ...
```
[consumer] --> [yanartas] --> [vfq]
```

Add functionality from the _service_ perspective (vfq, then yanartas, then consumer can use)
Remove functionality from the _customer's_ perspective (consumer stops using, then remove from yanartas, then vfq)

Merge this after Yanartas changes have been merged.

**Comment by bschofield-va** [comment]
`RawController` still references `site`

**Review by jhulbert-va — COMMENTED** [review]
```
vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/witnessprotection/RequestPayloadModifier.java:  private static final Pattern SITE_IN_PATH_PATTERN = Pattern.compile(".*/(hcs|site)/([-\\w]+)/.*");
```

**Review by jhulbert-va — APPROVED** [review]
Looks good to me.

@bschofield-va ?

**Pull request merged**
